### ISSUE TITLE
OSX High Sierra doesn't allow copying into `/usr/bin`

### ISSUE THREAD

**Issue by stephanschubert** [daedreth/ihsec#1]
I used `ln -sfr ihsec.sh /usr/local/bin/ihsec` instead. `cp` works also.

**Comment by daedreth** [comment]
does `install` work in OSX? If so, I will change it since it is also compatible with GNU/Linux.
Truth being told I never aimed to use this with MacOS or OSX, but if /usr/local/bin is a better destination to install it, I'll make a change.

**Comment by stephanschubert** [comment]
It fails here with:

```
sudo make
Password:
cp ihsec.sh /usr/bin/ihsec
cp: cannot create regular file '/usr/bin/ihsec': Operation not permitted
make: *** [bash] Error 1
```

**Comment by daedreth** [comment]
Should be fixed in latest commit, lemme know.

**Comment by stephanschubert** [comment]
```
sudo make
Password:
install -D -m 755 ihsec.sh /usr/local/bin/ihsec
```

Works 👍
